spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/focusflow}

server:
  port: ${PORT:8080}



# mongodb+srv://admin:WfWs9aoFky8N4Nky@focusflow.ujvk84u.mongodb.net/?appName=focusflow